import { SmartBin, UserProfile, SystemEvent, LeaderboardEntry, RewardItem } from './types';

export const INITIAL_BINS: SmartBin[] = [
  {
    id: 'BIN-101',
    name: 'Tech Park Block A',
    location: 'Building A Entrance',
    type: 'Commercial',
    dryFill: 42,
    wetFill: 88,
    overallFill: 65,
    battery: 92,
    weight: 14.2,
    moistureLevel: 78,
    isOnline: true,
    hasContamination: false,
    hasLiquidLeak: false,
    predictedFullHours: 3.5,
    lastUpdated: 'Just now',
  },
  {
    id: 'BIN-102',
    name: 'Greenwood Block B',
    location: 'Tower B Lobby',
    type: 'Residential',
    dryFill: 91,
    wetFill: 95,
    overallFill: 93,
    battery: 78,
    weight: 22.8,
    moistureLevel: 85,
    isOnline: true,
    hasContamination: true,
    hasLiquidLeak: true,
    predictedFullHours: 0.8,
    lastUpdated: 'Just now',
  },
  {
    id: 'BIN-103',
    name: 'Greenwood Gate 2',
    location: 'Residential Gate 2',
    type: 'Residential',
    dryFill: 25,
    wetFill: 30,
    overallFill: 28,
    battery: 45,
    weight: 6.5,
    moistureLevel: 20,
    isOnline: true,
    hasContamination: false,
    hasLiquidLeak: false,
    predictedFullHours: 18.2,
    lastUpdated: 'Just now',
  },
  {
    id: 'BIN-104',
    name: 'Central Plaza Park',
    location: 'North Walking Track',
    type: 'Public Park',
    dryFill: 70,
    wetFill: 12,
    overallFill: 41,
    battery: 88,
    weight: 9.1,
    moistureLevel: 15,
    isOnline: true,
    hasContamination: false,
    hasLiquidLeak: false,
    predictedFullHours: 7.4,
    lastUpdated: 'Just now',
  },
  {
    id: 'BIN-105',
    name: 'Clubhouse Quad',
    location: 'Sports Complex Lobby',
    type: 'Residential',
    dryFill: 15,
    wetFill: 10,
    overallFill: 12,
    battery: 15,
    weight: 2.1,
    moistureLevel: 10,
    isOnline: false,
    hasContamination: false,
    hasLiquidLeak: false,
    predictedFullHours: 42.0,
    lastUpdated: '2 hours ago',
  },
];

export const INITIAL_USER: UserProfile = {
  id: 'USR-8042',
  name: 'Sriram',
  userType: 'Resident',
  flatNo: 'A-402',
  ecoPoints: 450,
  ecoScore: 92,
  totalDisposals: 34,
  rank: 42,
  totalResidentsInApartment: 200,
};

export const TOP_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, name: 'Ananya Sharma', userType: 'Owner', flatNo: 'C-701', ecoPoints: 1450, ecoScore: 99 },
  { rank: 2, name: 'Vikram Mehta', userType: 'Resident', flatNo: 'B-304', ecoPoints: 1280, ecoScore: 97 },
  { rank: 3, name: 'Priya Sundaram', userType: 'Owner', flatNo: 'A-102', ecoPoints: 1150, ecoScore: 96 },
  { rank: 4, name: 'Rahul Verma', userType: 'Resident', flatNo: 'D-502', ecoPoints: 980, ecoScore: 95 },
  { rank: 5, name: 'Kavita Nair', userType: 'Owner', flatNo: 'C-203', ecoPoints: 890, ecoScore: 94 },
  { rank: 6, name: 'Arjun Patel', userType: 'Resident', flatNo: 'A-604', ecoPoints: 820, ecoScore: 94 },
  { rank: 7, name: 'Sneha Kulkarni', userType: 'Owner', flatNo: 'B-801', ecoPoints: 760, ecoScore: 93 },
  { rank: 8, name: 'Deepak Roy', userType: 'Resident', flatNo: 'D-101', ecoPoints: 710, ecoScore: 93 },
  { rank: 9, name: 'Meera Deshmukh', userType: 'Owner', flatNo: 'A-303', ecoPoints: 650, ecoScore: 92 },
  { rank: 10, name: 'Rohan Gupta', userType: 'Resident', flatNo: 'C-405', ecoPoints: 610, ecoScore: 92 },
];

export const AVAILABLE_REWARDS: RewardItem[] = [
  {
    id: 'REW-101',
    title: '₹200 Maintenance Fee Voucher',
    costPoints: 400,
    category: 'Apartment Perk',
    description: 'Direct credit towards your monthly apartment maintenance bill.',
  },
  {
    id: 'REW-102',
    title: 'Free Organic Compost Bag (5kg)',
    costPoints: 100,
    category: 'Gardening',
    description: 'Nutrient-rich organic compost produced from apartment wet waste.',
  },
  {
    id: 'REW-103',
    title: 'Clubhouse Event Pass',
    costPoints: 250,
    category: 'Lifestyle',
    description: 'Free 1-day pass for private event booking at the apartment clubhouse.',
  },
  {
    id: 'REW-104',
    title: 'Eco Champion Badge & Certificate',
    costPoints: 500,
    category: 'Recognition',
    description: 'Physical green certificate and plaque awarded at Society AGM.',
  },
  {
    id: 'REW-105',
    title: '₹100 Instant UPI Cash Voucher',
    costPoints: 300,
    category: 'Digital Cash',
    description: 'Direct UPI cash payout to your linked bank account.',
  },
  {
    id: 'REW-106',
    title: 'Plant a Sapling in Society Park',
    costPoints: 100,
    category: 'Green Impact',
    description: 'Sponsor a tree sapling planted with your name tag in the society garden.',
  },
  {
    id: 'REW-107',
    title: 'Public Transport Metro / Bus Pass',
    costPoints: 200,
    category: 'Commute',
    description: '1-day unlimited local public transport travel pass.',
  },
  {
    id: 'REW-108',
    title: 'Electricity & Utility Bill Discount',
    costPoints: 350,
    category: 'Utility Credit',
    description: '₹150 credit voucher applied to your monthly electricity bill.',
  },
];

export const INITIAL_EVENTS: SystemEvent[] = [
  {
    id: 'EVT-001',
    binId: 'BIN-102',
    timestamp: '16:45',
    type: 'OVERFILL_WARNING',
    message: 'Bin capacity reached 93%. Priority collection dispatched.',
    severity: 'critical',
  },
  {
    id: 'EVT-002',
    binId: 'BIN-102',
    timestamp: '16:40',
    type: 'CONTAMINATION_ALERT',
    message: 'Wet waste detected inside Dry Waste compartment.',
    severity: 'warning',
  },
  {
    id: 'EVT-003',
    binId: 'BIN-101',
    timestamp: '16:30',
    type: 'DISPOSAL_SUCCESS',
    message: 'Verified Dry Waste disposal (+10 EcoPoints).',
    severity: 'info',
  },
];
